const PRODUCTS = [
    {
        id: 1,
        name: 'Octopath Traveller',
        developer: 'Square Enix',
        image: './images/Octopath-traveler-cover.webp',
        vImage: './images/octopath_traveller_vertical.jpg',
        price: 79.99,
        salePrice: 79.99,
        sale: false,
        discount: '',
        platform: ['Nintedo Switch'],
        platform_i: '<i class="fa-solid fa-n"></i> <i class="fa-brands fa-steam"></i>',
        description: 'Square Enix has brought a new world to life through a mix of CG, pixel art, and "HD-2D" visuals. Embark on a vast new role-playing adventure as one of eight travelers, all with their own origins, paths, and goals. Where to begin? Who to team up with? Where to go next? Only you can decide.',

    },

    {
        id: 2,
        name: 'Cyberpunk 2077',
        developer: 'Projekt Red',
        image: './images/cyberpunk_2077_product_card.jpg',
        vImage: './images/Cyberpunk_2077_cover.jpg',
        price: 79.99,
        salePrice: 52.79,
        sale: true,
        discount: '34',
        platform: ['Xbox-One', 'PS5', 'Steam'],
        platform_i: '<i class="fa-brands fa-xbox"></i> <i class="fa-brands fa-playstation"></i> <i class="fa-brands fa-steam"></i>',
        description: 'Cyberpunk 2077 is an open-world, action-adventure story set in Night City. Become a cyberpunk, an urban mercenary equipped with cybernetic enhancements and build your legend on the streets of Night City. Take the riskiest job of your life and go after a prototype implant that is the key to immortality',
    },

    {
        id: 3,
        name: 'God of War: Ragnarok',
        developer: 'Sony',
        image: './images/GoW-Ragnarok_product_card.jpg',
        vImage: './images/God_of_War_Ragnarök_cover.jpg',
        price: 79.99,
        salePrice: 79.99,
        sale: false,
        discount: '',
        platform: ['PS5'],
        platform_i: '<i class="fa-brands fa-playstation"></i>',
        description: 'His vengeance against the gods of Olympus far behind him, Kratos now lives as a man in the lands of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same',
    },

    {
        id: 4,
        name: 'Horizon Zero Dawn',
        developer: 'Guerrilla Games',
        image: './images/horizon_zero_dawn_product_card.jpg',
        vImage: './images/horizon_zero_dawn_cover.jpg',
        price: 59.99,
        salePrice: 19.79,
        sale: true,
        discount: '67',
        platform: ['PS5', 'Steam'],
        platform_i: '<i class="fa-brands fa-playstation"></i> <i class="fa-brands fa-steam"></i>',
        description: 'Follow Aloy, a young hunter in a world overrun by machines, who sets out to uncover her past.',
    },

    {
        id: 5,
        name: 'Pokemon Violet',
        developer: 'Game Freak',
        image: './images/pokemon_violet_product_card.jpg',
        vImage: './images/pokemon_violet_cover.jpg',
        price: 79.99,
        salePrice: 79.99,
        sale: false,
        discount: '',
        platform: ['Nintedo Switch'],
        platform_i: '<i class="fa-solid fa-n"></i>',
        description: 'Embark on a new Pokémon adventure in an open world setting with your trusty partner Miraidon with three story lines! Battle powerful titans in Path of Legends, become the Champion through Victory Road, or discover the secrets behind the academy and the group of misfits, Team Star, through Starfall Street!',
    },

    {
        id: 6,
        name: 'Pokemon Scarlet',
        developer: 'Game Freak',
        image: './images/pokemon_scarlet_product_card.jpg',
        vImage: './images/pokemon_scarlet_cover.png',
        price: 79.99,
        salePrice: 79.99,
        sale: false,
        discount: '',
        platform: ['Nintedo Switch'],
        platform_i: '<i class="fa-solid fa-n"></i>',
        description: 'Embark on a new Pokémon adventure in an open world setting with your trusty partner Koraidon with three story lines! Battle powerful titans in Path of Legends, become the Champion through Victory Road, or discover the secrets behind the academy and the group of misfits, Team Star, through Starfall Street!',
    },

    {
        id: 7,
        name: 'Red Dead Redemption 2',
        developer: 'Rockstar Games',
        image: './images/red_dead_redemption_2_product_card.webp',
        vImage: './images/red_dead_redemption_2_cover.jpg',
        price: 79.99,
        salePrice: 26.39,
        sale: true,
        discount: '67',
        platform: ['Xbox-One, PS5, Steam'],
        platform_i: '<i class="fa-brands fa-xbox"></i> <i class="fa-brands fa-playstation"></i> <i class="fa-brands fa-steam"></i>',
        description: 'Developed by the creators of Grand Theft Auto V and Red Dead Redemption, Red Dead Redemption 2 is an epic tale of life in Americas unforgiving heartland. The games vast and atmospheric world will also provide the foundation for a brand new online multiplayer experience.',
    },

    {
        id: 8,
        name: 'Final Fantasy XIV: Endwalker',
        developer: 'Square Enix',
        image: './images/final_fantasy_xiv_product_card.png',
        vImage: './images/final_fantasy_xiv_cover.png',
        price: 39.99,
        salePrice: 39.99,
        sale: false,
        discount: '',
        platform: ['PS5, Windows, Steam'],
        platform_i: '<i class="fa-brands fa-playstation"> <i class="fa-brands fa-windows"></i> </i> <i class="fa-brands fa-steam"></i>',
        description: 'Experience the climax of the Hydaelyn and Zodiark story, and encounter an even greater calamity than ever before as you travel to the far reaches of Hydaelyn and even to the ends of the universe for one climactic finale!',
    },

    {
        id: 9,
        name: 'Elden Ring',
        developer: 'Fromsoft',
        image: './images/elden_ring_product_card.jpg',
        vImage: './images/elden_ring_cover.jpg',
        price: 79.99,
        salePrice: 52.79,
        sale: true,
        discount: '34',
        platform: ['PS5, Windows, Steam'],
        platform_i: '<i class="fa-brands fa-playstation"> <i class="fa-brands fa-windows"></i> </i> <i class="fa-brands fa-steam"></i>',
        description: 'Rise, tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
    },
];